export type ErrorCode =
	| "PEER_ALREADY_REGISTERED"
	| "PEER_NOT_FOUND"
	| "MESSAGE_NOT_FOUND"
	| "MESSAGE_NOT_IN_FLIGHT"
	| "VALIDATION_FAILED"
	| "INTERNAL_ERROR"
	| "TOPIC_NOT_FOUND"
	| "TOPIC_ALREADY_EXISTS"
	| "ALREADY_SUBSCRIBED"
	| "NOT_SUBSCRIBED"
	| "ISSUE_REPO_NOT_CONFIGURED"
	| "ISSUE_CLIENT_FAILED";

export const errorCodeToHttpStatus = {
	PEER_ALREADY_REGISTERED: 409,
	PEER_NOT_FOUND: 404,
	MESSAGE_NOT_FOUND: 404,
	MESSAGE_NOT_IN_FLIGHT: 409,
	VALIDATION_FAILED: 400,
	INTERNAL_ERROR: 500,
	TOPIC_NOT_FOUND: 404,
	TOPIC_ALREADY_EXISTS: 409,
	ALREADY_SUBSCRIBED: 409,
	NOT_SUBSCRIBED: 404,
	ISSUE_REPO_NOT_CONFIGURED: 412,
	ISSUE_CLIENT_FAILED: 502,
} as const satisfies Record<ErrorCode, number>;

export interface ApiError {
	code: ErrorCode;
	message: string;
	details?: unknown;
}

export type ApiResponse<T> =
	| ({ ok: true } & T)
	| { ok: false; error: ApiError };
